### ISSUE TITLE
Who will be the admin?

### ISSUE THREAD

**Issue by kyawzinthant-coding** [SwanHtetAungPhyo/BurmaGuru#2]
So when a user make a post, admin will check first before reaching out on the platform? But there can be a lot of posts if we get a lot of users and we have to verify every post.

**Comment by SwanHtetAungPhyo** [comment]
I am considering to make the automate bot admin 
 with the set of restriction by analyzing the keyword with LLM if the content is aggressive or 18 Plus.

**Comment by kyawzinthant-coding** [comment]
that is cool stuff that I have to learn.
