### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by kyawzinthant-coding** [SwanHtetAungPhyo/BurmaGuru#3]
There will be a dashboard too right? So admin will receive urgent alerts so websocket will come in ?

**Comment by SwanHtetAungPhyo** [comment]
I would like to use the hybrid admin for task like analyzing the error log on the API ,  adding new roles , category . Other task like approving the post  will be handled by the   bot

**Comment by kyawzinthant-coding** [comment]
I have no knowledge upon hybrid admin stuff but it sound cool .
