### ISSUE TITLE
Checlist

### ISSUE THREAD

**Issue by kyawzinthant-coding** [SwanHtetAungPhyo/BurmaGuru#5]
if a user wants to move aboard,  we will generated or give this user a checklist of things to prepare depend on their country.
They can also make checklist rt? It will be store along with user profile.

**Comment by SwanHtetAungPhyo** [comment]
Like the roadmap.sh as you said. I want the user to input their expectation  on the target country . 
That will be store d So, we will have the user's preference table along with user table
We will have the service layer that will make the analysis about whether is it possible to move or not .
If not , we will call the country api end point based on the user's expectations and suggest the other possible country to move.
